import type {
  ExampleRecord,
  RecipeData,
  RecipeFilter,
  RecipeLayer,
  RecipeModel,
  TraversalEdge,
} from './types'

export const MOCK_LAYERS: RecipeLayer[] = [
  { id: 'l1', label: 'Ownership' },
  { id: 'l2', label: 'Cloud geography' },
  { id: 'l3', label: 'Network' },
  { id: 'l4', label: 'Compute' },
  { id: 'l5', label: 'Traffic and policy' },
  { id: 'l6', label: 'Operations' },
]

export const MOCK_EXAMPLES: ExampleRecord[] = [
  {
    id: 'ex-bg-platform',
    label: 'Core Platform',
    kind: 'Business group',
    idValue: 'business_group:core-platform',
    isDefault: true,
  },
  {
    id: 'ex-bg-finance',
    label: 'Finance Systems',
    kind: 'Business group',
    idValue: 'business_group:finance-systems',
    isDefault: false,
  },
  {
    id: 'ex-bg-commerce',
    label: 'Digital Commerce',
    kind: 'Business group',
    idValue: 'business_group:digital-commerce',
    isDefault: false,
  },
  {
    id: 'ex-provider-aws',
    label: 'Amazon Web Services',
    kind: 'Cloud provider',
    idValue: 'cloud_provider:aws',
    isDefault: false,
  },
  {
    id: 'ex-provider-azure',
    label: 'Microsoft Azure',
    kind: 'Cloud provider',
    idValue: 'cloud_provider:azure',
    isDefault: false,
  },
  {
    id: 'ex-provider-gcp',
    label: 'Google Cloud Platform',
    kind: 'Cloud provider',
    idValue: 'cloud_provider:gcp',
    isDefault: false,
  },
  {
    id: 'ex-region-eu-central',
    label: 'eu-central-1',
    kind: 'Region',
    idValue: 'region:eu-central-1',
    isDefault: false,
  },
  {
    id: 'ex-env-prod',
    label: 'Production',
    kind: 'Environment',
    idValue: 'environment:production',
    isDefault: false,
  },
  {
    id: 'ex-server-api',
    label: 'api-prod-042',
    kind: 'Server',
    idValue: 'server:api-prod-042',
    isDefault: false,
  },
]

export const MOCK_MODELS: RecipeModel[] = [
  {
    id: 'business-group',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'BusinessGroup',
    modelId: 'infrastructure.BusinessGroup',
    displayName: 'Business Group',
    layerId: 'l1',
  },
  {
    id: 'environment',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'Environment',
    modelId: 'infrastructure.Environment',
    displayName: 'Environment',
    layerId: 'l1',
  },
  {
    id: 'cloud-provider',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'CloudProvider',
    modelId: 'infrastructure.CloudProvider',
    displayName: 'Cloud Provider',
    layerId: 'l2',
  },
  {
    id: 'region',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'Region',
    modelId: 'infrastructure.Region',
    displayName: 'Region',
    layerId: 'l2',
  },
  {
    id: 'network',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'Network',
    modelId: 'infrastructure.Network',
    displayName: 'Network',
    layerId: 'l3',
  },
  {
    id: 'subnet',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'Subnet',
    modelId: 'infrastructure.Subnet',
    displayName: 'Subnet',
    layerId: 'l3',
  },
  {
    id: 'server-template',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'ServerTemplate',
    modelId: 'infrastructure.ServerTemplate',
    displayName: 'Server Template',
    layerId: 'l4',
  },
  {
    id: 'server',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'Server',
    modelId: 'infrastructure.Server',
    displayName: 'Server',
    layerId: 'l4',
  },
  {
    id: 'load-balancer',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'LoadBalancer',
    modelId: 'infrastructure.LoadBalancer',
    displayName: 'Load Balancer',
    layerId: 'l5',
  },
  {
    id: 'security-group',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'SecurityGroup',
    modelId: 'infrastructure.SecurityGroup',
    displayName: 'Security Group',
    layerId: 'l5',
  },
  {
    id: 'security-rule',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'SecurityRule',
    modelId: 'infrastructure.SecurityRule',
    displayName: 'Security Rule',
    layerId: 'l5',
  },
  {
    id: 'monitoring-alert',
    appLabel: 'infrastructure',
    appVerboseName: 'Infrastructure',
    modelName: 'MonitoringAlert',
    modelId: 'infrastructure.MonitoringAlert',
    displayName: 'Monitoring Alert',
    layerId: 'l6',
  },
]

export const MOCK_EDGES: TraversalEdge[] = [
  {
    id: 'edge-business-group-environment',
    from: 'Business Group',
    to: 'Environment',
    fromModelId: 'business-group',
    toModelId: 'environment',
    via: 'environments',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-business-group-server',
    from: 'Business Group',
    to: 'Server',
    fromModelId: 'business-group',
    toModelId: 'server',
    via: 'servers',
    auto: true,
    cost: 2,
    alt: true,
  },
  {
    id: 'edge-business-group-network',
    from: 'Business Group',
    to: 'Network',
    fromModelId: 'business-group',
    toModelId: 'network',
    via: 'networks',
    auto: false,
    cost: 2,
    alt: true,
  },
  {
    id: 'edge-environment-network',
    from: 'Environment',
    to: 'Network',
    fromModelId: 'environment',
    toModelId: 'network',
    via: 'networks',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-environment-server',
    from: 'Environment',
    to: 'Server',
    fromModelId: 'environment',
    toModelId: 'server',
    via: 'servers',
    auto: false,
    cost: 2,
    alt: true,
  },
  {
    id: 'edge-environment-load-balancer',
    from: 'Environment',
    to: 'Load Balancer',
    fromModelId: 'environment',
    toModelId: 'load-balancer',
    via: 'load_balancers',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-cloud-provider-region',
    from: 'Cloud Provider',
    to: 'Region',
    fromModelId: 'cloud-provider',
    toModelId: 'region',
    via: 'regions',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-cloud-provider-template',
    from: 'Cloud Provider',
    to: 'Server Template',
    fromModelId: 'cloud-provider',
    toModelId: 'server-template',
    via: 'templates',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-region-network',
    from: 'Region',
    to: 'Network',
    fromModelId: 'region',
    toModelId: 'network',
    via: 'networks',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-network-subnet',
    from: 'Network',
    to: 'Subnet',
    fromModelId: 'network',
    toModelId: 'subnet',
    via: 'subnets',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-network-security-group',
    from: 'Network',
    to: 'Security Group',
    fromModelId: 'network',
    toModelId: 'security-group',
    via: 'security_groups',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-subnet-server',
    from: 'Subnet',
    to: 'Server',
    fromModelId: 'subnet',
    toModelId: 'server',
    via: 'servers',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-subnet-load-balancer',
    from: 'Subnet',
    to: 'Load Balancer',
    fromModelId: 'subnet',
    toModelId: 'load-balancer',
    via: 'load_balancers',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-server-template-server',
    from: 'Server Template',
    to: 'Server',
    fromModelId: 'server-template',
    toModelId: 'server',
    via: 'servers',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-load-balancer-server',
    from: 'Load Balancer',
    to: 'Server',
    fromModelId: 'load-balancer',
    toModelId: 'server',
    via: 'servers',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-security-group-server',
    from: 'Security Group',
    to: 'Server',
    fromModelId: 'security-group',
    toModelId: 'server',
    via: 'servers',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-security-group-rule',
    from: 'Security Group',
    to: 'Security Rule',
    fromModelId: 'security-group',
    toModelId: 'security-rule',
    via: 'rules',
    auto: true,
    cost: 1,
  },
  {
    id: 'edge-server-alert',
    from: 'Server',
    to: 'Monitoring Alert',
    fromModelId: 'server',
    toModelId: 'monitoring-alert',
    via: 'alerts',
    auto: true,
    cost: 1,
  },
]

export const MOCK_FILTERS: RecipeFilter[] = [
  {
    id: 'filter-business-group',
    layer: 'Business Group',
    expr: "cost_center__startswith = 'CC-'",
    suggested: false,
  },
  {
    id: 'filter-environment',
    layer: 'Environment',
    expr: "env_type__in = ['prod','stage']",
    suggested: false,
  },
  {
    id: 'filter-network',
    layer: 'Network',
    expr: 'is_active = true',
    suggested: true,
  },
  {
    id: 'filter-server',
    layer: 'Server',
    expr: "status__in = ['running','pending']",
    suggested: true,
  },
  {
    id: 'filter-alert',
    layer: 'Monitoring Alert',
    expr: 'is_resolved = false',
    suggested: false,
  },
]

export const MOCK_RECIPE: RecipeData = {
  title: 'Infrastructure Cloud Landscape',
  layers: MOCK_LAYERS,
  models: MOCK_MODELS,
  examples: MOCK_EXAMPLES,
  edges: MOCK_EDGES,
  filters: MOCK_FILTERS,
  groupRules: [
    {
      id: 'group-environments-by-business-group',
      parentModelId: 'business-group',
      childModelId: 'environment',
      via: 'environments',
    },
    {
      id: 'group-subnets-by-network',
      parentModelId: 'network',
      childModelId: 'subnet',
      via: 'subnets',
    },
    {
      id: 'group-rules-by-security-group',
      parentModelId: 'security-group',
      childModelId: 'security-rule',
      via: 'rules',
    },
  ],
  swatches: ['#C4006A', '#1D8B68', '#2563EB', '#8B5CF6', '#D97706', '#18181B'],
  layoutAlgorithm: 'Layered',
  promoteOrg: 'kaisommer',
  promoteVisibility: 'org-wide',
  promoteAudience: 'Platform, SRE, Security, Finance, and Commerce teams',
}
