# Generated by Django 6.0.1 on 2026-04-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stress_core", "0001_initial"),
        ("stress_dense_alpha", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeltaNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=140)),
                (
                    "alternate_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delta_alternate_nodes",
                        to="stress_core.stresstarget02",
                    ),
                ),
                (
                    "core_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delta_nodes",
                        to="stress_core.stresstarget01",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="stress_chain_delta.deltanode",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeltaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=140)),
                (
                    "alpha_hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delta_links",
                        to="stress_dense_alpha.alphahub",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="delta_links",
                        to="stress_core.stresstarget03",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="stress_chain_delta.deltanode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="stress_chain_delta.deltanode",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeltaBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=140)),
                (
                    "owner_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delta_bundles",
                        to="stress_core.stresstarget04",
                    ),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bundles",
                        to="stress_chain_delta.deltalink",
                    ),
                ),
                (
                    "preferred_link",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_for_bundle",
                        to="stress_chain_delta.deltalink",
                    ),
                ),
                (
                    "nodes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bundles",
                        to="stress_chain_delta.deltanode",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "name"],
            },
        ),
    ]
