# Generated by Django 6.0.1 on 2026-04-21 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stress_chain_delta", "0001_initial"),
        ("stress_dense_alpha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deltalink",
            name="alpha_hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="stress_dense_alpha.alphahub",
            ),
        ),
    ]
