# Generated by Django 6.0.1 on 2026-04-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StressAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("external_key", models.CharField(db_index=True, max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["dataset_label", "name"],
            },
        ),
        migrations.CreateModel(
            name="StressTarget01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget03",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget04",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget05",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget06",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget07",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget08",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget09",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget10",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget11",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget12",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget13",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget14",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget15",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget16",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget17",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget18",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget19",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget20",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget21",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget22",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget23",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget24",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget25",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget26",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget27",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget28",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget29",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget30",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget31",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget32",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget33",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget34",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget35",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StressTarget36",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=80)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="stress_core.stressanchor",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "ordinal", "name"],
                "abstract": False,
            },
        ),
    ]
