"""
Postprocessing hooks for drf-spectacular schema generation.

These hooks fix compatibility issues between the generated OpenAPI spec
and Orval's Zod code generator.
"""


def strip_readonly_from_response_schemas(result, generator, request, public):
    """
    Remove 'readOnly' from response-only component schemas.

    With COMPONENT_SPLIT_REQUEST=True, response schemas are never reused as
    request bodies. Orval's Zod generator ignores fields marked readOnly,
    which causes them to be stripped during parsing. Removing readOnly from
    response schemas fixes this without any semantic loss.
    """
    schemas = result.get("components", {}).get("schemas", {})
    # Request schemas generated by COMPONENT_SPLIT_REQUEST end with "Request"
    for schema_name, schema in schemas.items():
        if schema_name.endswith("Request"):
            continue
        _strip_readonly_recursive(schema)
    return result


def _strip_readonly_recursive(obj):
    """Recursively remove 'readOnly' keys from a schema dict."""
    if not isinstance(obj, dict):
        return
    obj.pop("readOnly", None)
    for value in obj.values():
        if isinstance(value, dict):
            _strip_readonly_recursive(value)
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    _strip_readonly_recursive(item)
