# Generated by Django 6.0.1 on 2026-04-21 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stress_chain_delta", "0001_initial"),
        ("stress_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpsilonCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("title", models.CharField(max_length=160)),
                (
                    "primary_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epsilon_primary_cards",
                        to="stress_core.stresstarget06",
                    ),
                ),
                (
                    "related_cards",
                    models.ManyToManyField(
                        blank=True,
                        related_name="referenced_by_cards",
                        to="stress_chain_epsilon.epsiloncard",
                    ),
                ),
                (
                    "secondary_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epsilon_secondary_cards",
                        to="stress_core.stresstarget07",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "title"],
            },
        ),
        migrations.CreateModel(
            name="EpsilonComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schema_stress_epsilon_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="stress_chain_epsilon.epsiloncard",
                    ),
                ),
                (
                    "mentioned_targets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="epsilon_comments",
                        to="stress_core.stresstarget08",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "id"],
            },
        ),
        migrations.CreateModel(
            name="EpsilonWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=140)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schema_stress_epsilon_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epsilon_workspaces",
                        to="stress_core.stresstarget05",
                    ),
                ),
                (
                    "root_delta_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="epsilon_workspaces",
                        to="stress_chain_delta.deltanode",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "name"],
            },
        ),
        migrations.AddField(
            model_name="epsiloncard",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="stress_chain_epsilon.epsilonworkspace",
            ),
        ),
    ]
