import type { HomeStats, Template } from './types'

// TODO: Replace with API call to generation-templates list endpoint
// Backend shape: GET /api/schema-viz/generation-templates/ → PaginatedGenerationTemplateQuickAccessEntryList
// Map: generationTemplate.name → title, generationTemplate.publishedBy → author,
//       generationTemplate.scope → promotion, version.steps[].nodeCount → nodes
export const MOCK_TEMPLATES: Template[] = [
  {
    id: 'tpl-sap',
    title: 'SAP Cloud Landscape',
    author: 'SchemaVIZ',
    nodes: 19,
    edges: 22,
    hue: 'pink',
    desc: 'Business groups → services → servers → data. Our flagship demo.',
    recent: true,
    promotion: 'featured',
    promotedBy: 'Platform team',
    promotedWhen: '2 weeks ago',
    usedBy: 142,
    starts: [
      { id: 'st-fin', label: 'Finance dept.', kind: 'Business group', count: 19 },
      { id: 'st-hr', label: 'HR dept.', kind: 'Business group', count: 14 },
      { id: 'st-s4', label: 'SAP S/4HANA', kind: 'Service', count: 22 },
      { id: 'st-eu', label: 'EU region', kind: 'Region', count: 27 },
    ],
  },
  {
    id: 'tpl-erd',
    title: 'E-commerce ERD',
    author: 'Mira K.',
    nodes: 14,
    edges: 18,
    hue: 'plum',
    desc: 'Orders, customers, products, inventory with FK relationships.',
    promotion: 'org',
    promotedBy: 'Mira K.',
    promotedWhen: '5 days ago',
    usedBy: 38,
    starts: [
      { id: 'st-ord', label: 'orders table', kind: 'Table', count: 14 },
      { id: 'st-cust', label: 'customers table', kind: 'Table', count: 11 },
    ],
  },
  {
    id: 'tpl-micro',
    title: 'Microservices Topology',
    author: 'Platform',
    nodes: 28,
    edges: 41,
    hue: 'green',
    desc: 'Service mesh with queues, gateways, and event buses.',
    promotion: 'featured',
    promotedBy: 'Platform team',
    promotedWhen: '1 month ago',
    usedBy: 96,
    starts: [
      { id: 'st-gw', label: 'edge-gateway', kind: 'Service', count: 28 },
      { id: 'st-pay', label: 'payments-svc', kind: 'Service', count: 12 },
      { id: 'st-evt', label: 'kafka.events', kind: 'Topic', count: 17 },
    ],
  },
  {
    id: 'tpl-stream',
    title: 'Streaming Pipeline',
    author: 'Data Team',
    nodes: 11,
    edges: 13,
    hue: 'pink',
    desc: 'Kafka → Flink → warehouse. Lineage flow, end to end.',
    promotion: 'org',
    promotedBy: 'Data team',
    promotedWhen: '3 weeks ago',
    usedBy: 24,
    starts: [{ id: 'st-src', label: 'events.source', kind: 'Topic', count: 11 }],
  },
  {
    id: 'tpl-domain',
    title: 'Domain Model: Insurance',
    author: 'Sofia R.',
    nodes: 22,
    edges: 30,
    hue: 'plum',
    desc: 'Aggregates, entities, and bounded contexts.',
    promotion: 'personal',
    starts: [
      { id: 'st-pol', label: 'Policy', kind: 'Aggregate', count: 22 },
      { id: 'st-clm', label: 'Claim', kind: 'Aggregate', count: 18 },
    ],
  },
  {
    id: 'tpl-iam',
    title: 'IAM & Permission Map',
    author: 'Security',
    nodes: 16,
    edges: 24,
    hue: 'green',
    desc: 'Roles, policies, and the resources they touch.',
    promotion: 'org',
    promotedBy: 'Security team',
    promotedWhen: '1 week ago',
    usedBy: 47,
    starts: [
      { id: 'st-role', label: 'role:admin', kind: 'Role', count: 16 },
      { id: 'st-bkt', label: 's3:prod-*', kind: 'Resource', count: 9 },
    ],
  },
  {
    id: 'tpl-multi',
    title: 'Multi-region Failover',
    author: 'SRE',
    nodes: 9,
    edges: 12,
    hue: 'pink',
    desc: 'Primary, replicas, and the traffic that fails over.',
    promotion: 'team',
    promotedBy: 'SRE',
    promotedWhen: '2 days ago',
    usedBy: 6,
    starts: [{ id: 'st-pri', label: 'primary-eu', kind: 'Region', count: 9 }],
  },
]

// TODO: Replace with API call to stats/summary endpoint
export const MOCK_STATS: HomeStats = {
  templateCount: 248,
  ownedLandscapes: 12,
  sharedWithYou: 34,
  nodePresets: 6,
}
