# Generated by Django 6.0.1 on 2026-04-21 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stress_core", "0001_initial"),
        (
            "stress_dense_alpha",
            "0002_remove_alphahub_reviewer_alphahub_secondary_anchor",
        ),
        ("stress_dense_gamma", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gammahub",
            name="reviewer",
        ),
        migrations.AddField(
            model_name="gammahub",
            name="secondary_anchor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_secondary_items",
                to="stress_core.stressanchor",
            ),
        ),
        migrations.AlterField(
            model_name="gammahub",
            name="alpha_hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="stress_dense_alpha.alphahub",
            ),
        ),
    ]
