# Generated by Django 6.0.1 on 2026-04-25 10:11

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


SEEDED_TOUR_KEYS = [
    "canvas-onboarding",
    "node-workflow",
    "schema-workflow",
    "generation-workflow",
    "start-screen-onboarding",
    "workspace-navigation",
    "keyboard-shortcuts",
]


def seed_default_tours(apps, schema_editor):
    TourDefinition = apps.get_model("django_schema_viz", "TourDefinition")
    for key in SEEDED_TOUR_KEYS:
        TourDefinition.objects.update_or_create(
            key=key,
            version=1,
            defaults={"is_active": True},
        )


def remove_default_tours(apps, schema_editor):
    TourDefinition = apps.get_model("django_schema_viz", "TourDefinition")
    TourDefinition.objects.filter(key__in=SEEDED_TOUR_KEYS, version=1).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("react_flow_state", models.JSONField(default=dict)),
                ("lexical_state", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationTemplate",
            fields=[
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "root_model",
                    models.CharField(
                        help_text='The starting model for traversal, e.g. "infrastructure.Server"',
                        max_length=200,
                    ),
                ),
                (
                    "export_name",
                    models.SlugField(
                        blank=True,
                        help_text="Unique slug used in export URLs, e.g. export/schema_viz/my-template",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=dict,
                        help_text="Tree of traversal steps defining relationships, visibility, and style templates",
                    ),
                ),
                (
                    "layout_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Layout preferences, e.g. {"algorithm": "horizontal", "spacing": 40}',
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Global templates are available to all users",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured templates appear as quick access recommendations on the start page.",
                    ),
                ),
                (
                    "feature_rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional manual ordering for featured templates. Lower ranks appear first.",
                        null=True,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_generation_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "root_model",
                    models.CharField(
                        help_text='The starting model for traversal, e.g. "infrastructure.Server"',
                        max_length=200,
                    ),
                ),
                (
                    "definition",
                    models.JSONField(
                        default=dict,
                        help_text="Normalized generation graph definition keyed by step id.",
                    ),
                ),
                (
                    "layout_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Layout preferences, e.g. {"algorithm": "horizontal", "spacing": 40}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="django_schema_viz.generationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="generationtemplate",
            name="draft_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="draft_for_templates",
                to="django_schema_viz.generationtemplateversion",
            ),
        ),
        migrations.AddField(
            model_name="generationtemplate",
            name="published_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_for_templates",
                to="django_schema_viz.generationtemplateversion",
            ),
        ),
        migrations.CreateModel(
            name="SchemaVizUserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")],
                        default="en",
                        max_length=8,
                    ),
                ),
                ("help_hints_enabled", models.BooleanField(default=True)),
                ("help_hints_dismissed", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_viz_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="StyleTemplate",
            fields=[
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "visual_styles",
                    models.JSONField(
                        default=dict,
                        help_text="CSS properties: colors, borders, backgrounds, etc.",
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        default=dict, help_text="Default width and height of the node"
                    ),
                ),
                (
                    "type_specific_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Node-type specific data such as shape and shape colors.",
                    ),
                ),
                (
                    "text_content",
                    models.JSONField(
                        blank=True,
                        help_text="Lexical editor state, may reference model fields via {{field_name}}",
                        null=True,
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of model field names this template needs, e.g. ['hostname', 'ip_address']",
                    ),
                ),
                (
                    "is_model_exclusive",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, this template can only be applied to the selected target model.",
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Global templates are available to all users",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured templates are highlighted as recommended company defaults.",
                    ),
                ),
                (
                    "feature_rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional manual ordering for featured templates. Lower ranks appear first.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional forced model target when exclusive mode is enabled.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="style_templates_targeted",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelTemplateDefault",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_template_defaults",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_template_defaults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "style_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_defaults",
                        to="django_schema_viz.styletemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StyleTemplateFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "style_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_entries",
                        to="django_schema_viz.styletemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_template_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=120)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key", "-version"],
                "indexes": [
                    models.Index(
                        fields=["key", "is_active"], name="django_sche_key_6bbd75_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "version"),
                        name="uniq_tour_definition_key_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TourProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=0)),
                ("highest_step", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="django_schema_viz.tourdefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentSyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                ("source", models.JSONField(blank=True, default=dict)),
                ("selection", models.JSONField(blank=True, default=dict)),
                ("bundle_hash", models.CharField(max_length=64)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schema_viz_environment_sync_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["bundle_hash"], name="django_sche_bundle_0f0792_idx"
                    ),
                    models.Index(
                        fields=["actor_username", "-created_at"],
                        name="django_sche_actor_u_d5a8d3_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="django_sche_status_d71f9a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GenerationTemplateFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_entries",
                        to="django_schema_viz.generationtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_template_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "generation_template"),
                        name="uniq_generation_template_favorite_per_user",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="generationtemplateversion",
            index=models.Index(
                fields=["template", "-version_number"],
                name="django_sche_templat_f43962_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generationtemplateversion",
            index=models.Index(
                fields=["root_model"], name="django_sche_root_mo_51798d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version_number"),
                name="uniq_generation_template_version_number",
            ),
        ),
        migrations.AddIndex(
            model_name="generationtemplate",
            index=models.Index(
                fields=["is_global", "owner"], name="django_sche_is_glob_88a8eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationtemplate",
            index=models.Index(
                fields=["is_featured", "feature_rank"],
                name="django_sche_is_feat_f32541_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generationtemplate",
            index=models.Index(
                fields=["root_model"], name="django_sche_root_mo_300fde_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("owner"),
                condition=models.Q(("is_global", False)),
                name="uniq_generation_template_name_owner_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("is_global", True)),
                name="uniq_generation_template_name_global_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("export_name"),
                models.F("owner"),
                condition=models.Q(
                    ("export_name__isnull", False), ("is_global", False)
                ),
                name="uniq_generation_template_export_name_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("export_name"),
                condition=models.Q(("export_name__isnull", False), ("is_global", True)),
                name="uniq_generation_template_export_name_global",
            ),
        ),
        migrations.AddIndex(
            model_name="styletemplate",
            index=models.Index(
                fields=["is_global", "owner"], name="django_sche_is_glob_127e76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="styletemplate",
            index=models.Index(
                fields=["is_featured", "feature_rank"],
                name="django_sche_is_feat_59ec21_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="styletemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("owner"),
                condition=models.Q(("is_global", False)),
                name="uniq_style_template_name_owner_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="styletemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("is_global", True)),
                name="uniq_style_template_name_global_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="modeltemplatedefault",
            index=models.Index(
                fields=["owner", "content_type"], name="django_sche_owner_i_8deeb9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="modeltemplatedefault",
            constraint=models.UniqueConstraint(
                fields=("owner", "content_type"),
                name="uniq_model_template_default_owner_content_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="styletemplatefavorite",
            constraint=models.UniqueConstraint(
                fields=("user", "style_template"),
                name="uniq_style_template_favorite_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="tourprogress",
            index=models.Index(
                fields=["user", "status"], name="django_sche_user_id_39365e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tourprogress",
            constraint=models.UniqueConstraint(
                fields=("tour", "user"), name="uniq_tour_progress_per_user"
            ),
        ),
        migrations.RunPython(
            code=seed_default_tours,
            reverse_code=remove_default_tours,
        ),
    ]
