# Generated by Django 6.0.1 on 2026-05-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_schema_viz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemavizuserpreference',
            name='ai_api_key_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schemavizuserpreference',
            name='ai_base_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='schemavizuserpreference',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
