# Generated by Django 6.0.1 on 2026-05-05 15:29

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_schema_viz', '0002_ai_config_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTemplate',
            fields=[
                ('revision', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('background_color', models.CharField(default='rgba(255, 255, 255, 0.1)', help_text='Background color of the group container.', max_length=50)),
                ('background_opacity', models.FloatField(default=1.0, help_text='Opacity multiplier for the background (0.0 - 1.0).')),
                ('border_color', models.CharField(default='rgba(23, 18, 20, 0.14)', help_text='Border color of the group.', max_length=50)),
                ('border_width', models.FloatField(default=1.0, help_text='Border width in px.')),
                ('border_style', models.CharField(default='solid', help_text='CSS border-style: solid, dashed, dotted, etc.', max_length=20)),
                ('border_radius', models.PositiveIntegerField(default=10, help_text='Border radius in px.')),
                ('padding_top', models.PositiveIntegerField(default=48, help_text='Top padding in px (includes label area).')),
                ('padding_x', models.PositiveIntegerField(default=16, help_text='Horizontal padding (left and right) in px.')),
                ('padding_bottom', models.PositiveIntegerField(default=16, help_text='Bottom padding in px.')),
                ('label_font_size', models.PositiveIntegerField(default=14, help_text='Font size of the group label in px.')),
                ('label_color', models.CharField(default='rgba(23, 18, 20, 0.82)', help_text='Text color of the group label.', max_length=50)),
                ('text_content', models.JSONField(blank=True, help_text='Optional Lexical editor state for the group label text.', null=True)),
                ('child_columns', models.PositiveIntegerField(default=3, help_text='Number of columns for the child grid layout.')),
                ('child_gap_x', models.PositiveIntegerField(default=16, help_text='Horizontal gap between children in px.')),
                ('child_gap_y', models.PositiveIntegerField(default=20, help_text='Vertical gap between children in px.')),
                ('child_direction', models.CharField(default='grid', help_text='Layout direction for children: grid, horizontal, or vertical.', max_length=20)),
                ('is_global', models.BooleanField(default=False, help_text='Global templates are available to all users.')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured templates are highlighted as recommended company defaults.')),
                ('feature_rank', models.PositiveIntegerField(blank=True, help_text='Optional ordering for featured templates. Lower ranks appear first.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_global', 'owner'], name='django_sche_is_glob_66ed12_idx'), models.Index(fields=['is_featured', 'feature_rank'], name='django_sche_is_feat_216d6c_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), condition=models.Q(('is_global', False)), name='uniq_group_template_name_owner_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_global', True)), name='uniq_group_template_name_global_ci')],
            },
        ),
    ]
