# Generated by Django 6.0.1 on 2026-05-06 05:48

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_schema_viz", "0004_remove_environment_sync_run"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="generationtemplate",
            name="uniq_generation_template_export_name_owner",
        ),
        migrations.RemoveConstraint(
            model_name="generationtemplate",
            name="uniq_generation_template_export_name_global",
        ),
        migrations.AddConstraint(
            model_name="generationtemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("export_name"),
                condition=models.Q(("export_name__isnull", False)),
                name="uniq_generation_template_export_name_ci",
            ),
        ),
    ]
