/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBuilderRouteImport } from './routes/_app/builder'
import { Route as GenerateSlugIndexRouteImport } from './routes/generate/$slug.index'
import { Route as GenerateSlugRecordIdRouteImport } from './routes/generate/$slug.$recordId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuilderRoute = AppBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppRoute,
} as any)
const GenerateSlugIndexRoute = GenerateSlugIndexRouteImport.update({
  id: '/generate/$slug/',
  path: '/generate/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateSlugRecordIdRoute = GenerateSlugRecordIdRouteImport.update({
  id: '/generate/$slug/$recordId',
  path: '/generate/$slug/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/mcp': typeof McpRoute
  '/builder': typeof AppBuilderRoute
  '/generate/$slug/$recordId': typeof GenerateSlugRecordIdRoute
  '/generate/$slug/': typeof GenerateSlugIndexRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/builder': typeof AppBuilderRoute
  '/': typeof AppIndexRoute
  '/generate/$slug/$recordId': typeof GenerateSlugRecordIdRoute
  '/generate/$slug': typeof GenerateSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/mcp': typeof McpRoute
  '/_app/builder': typeof AppBuilderRoute
  '/_app/': typeof AppIndexRoute
  '/generate/$slug/$recordId': typeof GenerateSlugRecordIdRoute
  '/generate/$slug/': typeof GenerateSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/builder'
    | '/generate/$slug/$recordId'
    | '/generate/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/builder'
    | '/'
    | '/generate/$slug/$recordId'
    | '/generate/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/mcp'
    | '/_app/builder'
    | '/_app/'
    | '/generate/$slug/$recordId'
    | '/generate/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  McpRoute: typeof McpRoute
  GenerateSlugRecordIdRoute: typeof GenerateSlugRecordIdRoute
  GenerateSlugIndexRoute: typeof GenerateSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builder': {
      id: '/_app/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AppBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/generate/$slug/': {
      id: '/generate/$slug/'
      path: '/generate/$slug'
      fullPath: '/generate/$slug/'
      preLoaderRoute: typeof GenerateSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/$slug/$recordId': {
      id: '/generate/$slug/$recordId'
      path: '/generate/$slug/$recordId'
      fullPath: '/generate/$slug/$recordId'
      preLoaderRoute: typeof GenerateSlugRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBuilderRoute: typeof AppBuilderRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuilderRoute: AppBuilderRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  McpRoute: McpRoute,
  GenerateSlugRecordIdRoute: GenerateSlugRecordIdRoute,
  GenerateSlugIndexRoute: GenerateSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
