# Generated by Django 6.0.1 on 2026-04-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stress_chain_delta", "0001_initial"),
        ("stress_core", "0001_initial"),
        ("stress_dense_alpha", "0001_initial"),
        ("stress_dense_beta", "0001_initial"),
        ("stress_dense_gamma", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZetaScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=140)),
                (
                    "alpha_hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zeta_scenarios",
                        to="stress_dense_alpha.alphahub",
                    ),
                ),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zeta_scenarios",
                        to="stress_core.stressanchor",
                    ),
                ),
                (
                    "beta_hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zeta_scenarios",
                        to="stress_dense_beta.betahub",
                    ),
                ),
                (
                    "gamma_hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zeta_scenarios",
                        to="stress_dense_gamma.gammahub",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "name"],
            },
        ),
        migrations.CreateModel(
            name="ZetaStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                ("name", models.CharField(max_length=140)),
                (
                    "fanout_targets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="zeta_steps",
                        to="stress_core.stresstarget09",
                    ),
                ),
                (
                    "gateway_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zeta_gateway_steps",
                        to="stress_core.stresstarget10",
                    ),
                ),
                (
                    "previous_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_steps",
                        to="stress_chain_zeta.zetastep",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="stress_chain_zeta.zetascenario",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "scenario", "id"],
            },
        ),
        migrations.CreateModel(
            name="ZetaCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_label", models.SlugField()),
                (
                    "delta_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zeta_checkpoints",
                        to="stress_chain_delta.deltabundle",
                    ),
                ),
                (
                    "review_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zeta_checkpoints",
                        to="stress_core.stresstarget11",
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependent_checkpoints",
                        to="stress_chain_zeta.zetastep",
                    ),
                ),
                (
                    "step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoint",
                        to="stress_chain_zeta.zetastep",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_label", "step"],
            },
        ),
    ]
